//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slanje
    {
        public int SlanjeId { get; set; }
        public Nullable<int> KlijentId { get; set; }
        public string Adresa { get; set; }
        public string Grad { get; set; }
        public string Zemlja { get; set; }
        public string PK { get; set; }
        public Nullable<int> NarudzbinaId { get; set; }
        public Nullable<decimal> Vrednost { get; set; }
        public string Placanje { get; set; }
    
        public virtual Klijent Klijent { get; set; }
    }
}
