//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusKorpe
    {
        public int StatusKorpeId { get; set; }
        public string StatusKorpe1 { get; set; }
    }
}
